### ISSUE TITLE
Unexpected char 

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#331] opened 2019-09-09 15:39 UTC
I get this error and I dont know why. The whole stacktrace only shows this:

```
17:33:00,373 SEVERE [org.eclipse.yasson.internal.Unmarshaller] 
Unexpected char 119 at (line no=1, column no=2, offset=1), expecting 'r'
17:33:00,373 ERROR [my.Utils]
 javax.json.bind.JsonbException: Internal error: Unexpected char 119 at (line no=1, column no=2, offset=1), expecting 'r'
```

**Comment by aguibert** [comment] 2019-09-09 20:55
hi @nimo23, to proceed we will need to get more info. Is the `my.Utils` class burying the exception?  We will need to print the full stack trace somehow.

When an internal error occurs on deserialization, we wrap it in a `JsonbException` but still keep the original exception as a causedBy:
```java
        } catch (Exception e) {
            logger.severe(e.getMessage());
            throw new JsonbException(Messages.getMessage(MessageKeys.INTERNAL_ERROR, e.getMessage()), e);
        }
```

**Comment by nimo23** [comment] 2019-09-09 21:01
Hi,

this is the full stacktrace. No more info is provided by yasson. The my.Utils calls the following method (which works for different entities):

```
public static <T> T fromJsonToObject(String json, Class<T> clazz) {
		try (var jsonb = JsonbBuilder.create()) {
			return jsonb.fromJson(json, clazz);
		} catch (Exception e) {
			log.error(e);
			return null;
		}
	}
```

**Comment by aguibert** [comment] 2019-09-13 18:05
hi @nimo23, I"m not sure what logging framework you are using, but it is fairly common for loggers to only log the exception message and not the full stack trace. Try adding a `e.printStackTrace()` or something.

Also, I see you are calling `JsonbBuilder.create()` on each invocation of this method. This will cause very poor performance, since `Jsonb` instances are supposed to be cached. I suggest you initialize your `Jsonb` instance as `static final Jsonb jsonb = JsonbBuilder.create()` (don't need to worry about closing it in a try-with-resource block)

**Comment by nimo23** [comment] 2019-09-13 18:20
I use jboss logging provided by wildfly container..

`e.printStackTrace ` instead of log.error(e) ? Really? I think, `e` also logs the full stacktrace. I did not use `e.getMessage()` but `e` which should also print the full stacktrace like `e.printStacktrace`. And using e.printStacktrace instead of log.error() is not good practice. 
https://stackoverflow.com/questions/10477607/avoid-printstacktrace-use-a-logger-call-instead


> I see you are calling JsonbBuilder.create()

thanks for the tip.

**Comment by jbescos** [comment] 2019-11-07 13:43
@nimo23 could you copy-paste the JSON you are parsing?. Is it possible that the JSON doesn't have double quotes in a key?. Next example would fail with the same error you have:
`{test:"any"}`
The correct format would be:
`{"test":"any"}`

`Caused by: javax.json.stream.JsonParsingException: Unexpected char 101 at (line no=2, column no=2, offset=3), expecting 'r'
	at org.glassfish.json.JsonTokenizer.expectedChar(JsonTokenizer.java:583)
	at org.glassfish.json.JsonTokenizer.readTrue(JsonTokenizer.java:281)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:366)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:442)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:352)
	at org.eclipse.yasson.internal.JsonbRiParser.next(JsonbRiParser.java:143)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:75)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:60)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
	... 27 more`

It happens

**Comment by nimo23** [comment] 2019-11-07 14:02
@jbescos  i cannot trace the error anymore because I did forget the origin json data causing that error...the problem with this is also that the stacktrace produced by yasson did and does not provide more information than needed to trace the error..

**Comment by nimo23** [comment] 2019-11-07 17:44
thanks. good to know..I assumed that
 `log.error(e);` prints same stacktrace as `log.error("Unexpected error", e);`

**Comment by aguibert** [comment] 2019-11-07 21:52
Good catch @jbescos, calling `log.error(e)` where `e` is an Exception will invoke `org.jboss.logging.Logger.error(Object o)`
which logs the `toString()` of the passed in object which for Exceptions is just the caused by.

**Comment by aguibert** [comment] 2020-03-28 16:12
Closing this issue because there hasn't been any activity for a while and it seems the confusion was caused by calling the incorrect logging method on the user end.

**Closed by aguibert** 2020-03-28 16:12 UTC
Labels: invalid

**Comment by prudhvidhar18** [comment] 2023-11-13 17:34
javax.json.stream.JsonParsingException: Unexpected char 80 at (line no=1, column no=12, offset=11)


Hello I am getting this Error . could you please help me
