### ISSUE TITLE
Caused by: java.lang.StackOverflowError while converting toJson

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#299] opened 2019-08-09 12:49 UTC
Another `java.lang.StackOverflowError` from a bean hierarchy (works in jackson, fails in yasson). Yasson does not show which property makes the trouble. I cannot find the error at the moment. The stacktrace shows nothing but this:

```
Caused by: java.lang.StackOverflowError
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.DefaultSerializers.findByCondition(DefaultSerializers.java:130)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.DefaultSerializers.findValueSerializerProvider(DefaultSerializers.java:126)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.SerializerBuilder.getSupportedTypeSerializer(SerializerBuilder.java:149)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.SerializerBuilder.build(SerializerBuilder.java:85)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:102)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:103)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:103)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:103)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)

```

**Comment by aguibert** [comment] 2019-08-09 18:24
hi @nimo23, can you please include the Java models for the classes you are using?

**Comment by nimo23** [comment] 2019-08-11 01:05
I found the error: It s because of circular dependencies between classes. In my case it was a **indirect** ciruclar dependeny.

A direct circular dependency example:

public class User{
    private Task task;
    ...
}

public class Task {
    private User user;
    ...
}

// creates java.lang.StackOverflowError, as it s going from user->task->user->..
jsonb.toJson(user)

// creates java.lang.StackOverflowError, as it s going from taks->user->taks->..
jsonb.toJson(taks)

A solution would be: provide at least feedback which property has circular dependency and stop the processing in such cases..

**Comment by aguibert** [comment] 2019-08-11 03:19
I am curious, when you say this "works in Jackson", what does Jackson produce? Does it stop serializing data once a cycle is reached?

I think we should add circular dependency checking to Yasson, there are a few ways we could do this:
1. Throw a JsonbException if a cycle is detected (better than let it StackOverflow or OOM)
2. Stop processing the JSON if a cycle is detected
3. Use JSON Pointers (being considered at the spec level here: https://github.com/eclipse-ee4j/jsonb-api/issues/72)

Of the 3 options, I think option (3) using JSON Pointers would be the best approach.

**Comment by nimo23** [comment] 2019-08-11 07:58
>Does it stop serializing data once a cycle is reached?
There were a @JsonIgnore on the other side..

>I think option (3) 

yes, would be the best

**Comment by aguibert** [comment] 2019-08-11 16:57
The JSON-B equivalent to Jackson's `@JsonIgnore` is the `@JsonbTransient` annotation. So if you put `@JsonbTransient` on the other side, it should work the same as Jackson did.

For example, this code works for me:
```java
    public static class Foo {
        public String name = "foo";
        @JsonbTransient
        public Foo self;
    }

// ...
        Foo foo = new Foo();
        foo.self = foo;
        System.out.println(jsonb.toJson(foo)); // {"name":"foo"}

```

**Comment by nimo23** [comment] 2019-08-11 17:20
hi. yes I know. However, I did not find the trouble made prop immediatly..

Would be nice to solve circulare deps with JSON Pointers because putting @JsonbTransient at the other side prevents json processing for this property in all cases even if I select the the other side as the root for json processing. 

```
public class Task {
    //
    @JsonbTransient
    private User user;
    ...
}
```

```
// (de)serialize "user->taks"
jsonb.toJson(user
```

```
// should (de)serialize "taks->user" but user cannot be processed because of @JsonbTransient
jsonb.toJson(taks)
```

With JSON Pointers I am not forced to put `@JsonbTransient` on the other side..

**Comment by aguibert** [comment] 2019-08-13 20:47
Closing this item as a duplicate of #297 (Include property name when a property fails to serialize)

If we eliminate the fact that the property name is not included when serialization fails, the behavior here is the same as Jackson, because with either library the user must add an annotation to ignore the property that leads to the circular reference. Earlier in the issue we also discussed the possibility of better handling this via JSON Pointers, but that item is already tracked at the spec level and would be an enhancement rather than a bug.

**Closed by aguibert** 2019-08-13 20:47 UTC
Labels: duplicate
