### ISSUE TITLE
Premature EOF

### ISSUE THREAD

**Issue by garrettahines1** [eclipse-ee4j/yasson#361] opened 2019-11-18 21:51 UTC
**Describe the bug**
Sometimes when de-serializing a large amount of data, a permature EOF IOException is thrown. The same data can pass and fail.

**To Reproduce**
Using Yasson to deserialize things over a REST endpoint. Return large amount of data and try a couple times until error is thrown.

**Expected behavior**
Json data is succesfully de-serialized every time.

**System information:**
 - OS: Windows
 - Java Version: 11
 - Yasson Version: 1.0.5

**Additional context**
```
Caused by: javax.json.bind.JsonbException: Internal error: I/O error while parsing JSON
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:74)
        at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:54)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:93)
        at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:70)
        ... 79 more
Caused by: javax.json.JsonException: I/O error while parsing JSON
        at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:466)
        at org.glassfish.json.JsonTokenizer.readNumberChar(JsonTokenizer.java:219)
        at org.glassfish.json.JsonTokenizer.readNumber(JsonTokenizer.java:248)
        at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:389)
        at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:535)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:352)
        at org.eclipse.yasson.internal.JsonbRiParser.next(JsonbRiParser.java:143)
        at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:75)
        at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:60)
        at org.eclipse.yasson.internal.serializer.ObjectDeserializer.deserializeNext(ObjectDeserializer.java:174)
        at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:84)
        at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:60)
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
        ... 83 more
Caused by: java.io.IOException: Premature EOF
        at java.base/sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
        at java.base/sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
        at java.base/sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3495)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper.read(AbstractBuiltResponse.java:580)
        at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:99)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
        at org.glassfish.json.JsonTokenizer.fillBuf(JsonTokenizer.java:495)
        at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:456)
        ... 95 more
```
https://stackoverflow.com/questions/12335687/java-io-ioexception-premature-eof-in-rest-in-java-using-jersey stackoverflow that seems similar to my issue

**Comment by aguibert** [comment] 2019-11-20 21:25
hi @garrettahines1, thanks for raising this issue. Approximately what size are the payloads your application is reading, and what is the max heap size of your JVM?

**Comment by aguibert** [comment] 2019-11-20 21:29
also, are there any interesting characteristics about the payload? For example:
 - large number of small properties
 - deeply nested object structure
 - very large properties (i.e. a 10000 char string)
 - what data types are being unmarshalled into (e.g. String, arrays, collections, byte arrays, etc)

**Comment by garrettahines1** [comment] 2019-11-20 22:05
Using the default java heap size for java 11 and the data structure is mostly a large array of doubles and each double is relatively small, usually no more than 20 digits.

**Comment by jbescos** [comment] 2019-11-22 13:02
@garrettahines1 from your stack trace, I imagine that you are connecting to that REST server with an HTTP client (resty) and you are having that exception in the client. Did you check the server logs?, maybe there is some relevant information there.

Just to discard there is nothing wrong in server side, could you try with a different HTTP client?, for example with curl. If you are able to do this, could you attach the obtained JSON so we can use it in a test?.

I have tried it with a big array of doubles but I don't get any error. I put it here if you want to try it or make modifications:
```
    @Test
    public void bigStream() throws UnknownHostException, IOException, InterruptedException {
        final int PORT = 16666;
        final int ITERATIONS = 10000000;
        CountDownLatch latch = new CountDownLatch(1);
        Executors.newSingleThreadExecutor().execute(() -> {
            try(ServerSocket server = new ServerSocket(PORT)) {
                latch.countDown();
                try(Socket socket = server.accept(); PrintWriter writer = new PrintWriter(socket.getOutputStream())){
                    writer.write("[");
                    for(int i=0;i<ITERATIONS;i++) {
                        if(i != 0) {
                            writer.write(",");
                        }
                        writer.write(new Double(546546.984849).toString());
                        if(i % (ITERATIONS/10) == 0) {
                            writer.flush();
                        }
                    }
                    writer.write("]");
                    writer.flush();
                }
            } catch (IOException e) {
                System.out.println("Server socket is closed: "+e.getMessage());
            }
        });
        latch.await();
        try(Socket socket = new Socket(InetAddress.getLocalHost(), PORT)){
            System.out.println("Socket start reading");
            Double[] response = jsonb.fromJson(socket.getInputStream(), new Double[0].getClass());
            assertEquals(ITERATIONS, response.length);
            System.out.println("Socket stop reading");
        }
    }
```

**Comment by aguibert** [comment] 2020-03-28 16:05
Closing this issue since there hasn't been any activity for a while. Based on the stack trace it seems that the issue is in the HTTP layer where the input stream is getting cut short and Yasson is simply surfacing that error.

**Closed by aguibert** 2020-03-28 16:05 UTC
Labels: bug
