### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by jefrog1844** [eclipse-ee4j/yasson#420] opened 2020-06-16 16:51 UTC
**Describe the bug**
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled

2020-06-16 11:29:09,961 INFO  [io.agr.pool] (Quarkus Main Thread) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
2020-06-16 11:29:16,316 INFO  [io.quarkus] (Quarkus Main Thread) podfx 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.5.0.Final) started in 9.655s. Listening on: http://0.0.0.0:9080
2020-06-16 11:29:16,316 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-06-16 11:29:16,316 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, mutiny, narayana-jta, resteasy, resteasy-jsonb, security, smallrye-jwt, vertx, vertx-web]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (jar:file:/C:/Users/019535/.m2/repository/org/eclipse/yasson/1.0.7/yasson-1.0.7.jar!/) to constructor java.util.AbstractCollection()
WARNING: Please consider reporting this to the maintainers of org.eclipse.yasson.internal.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**To Reproduce**
Steps to reproduce the bug

**Expected behavior**

**System information:**
 - OS: Windows 7
 - Java Version:  11
 - Yasson Version: 1.0.7

**Additional context**

**Comment by Degubi** [comment] 2020-06-17 19:36
This is a duplicate of #412, which was already resolved & closed

**Comment by aguibert** [comment] 2020-06-18 02:27
What @Degubi said 🙂

**Closed by aguibert** 2020-06-18 02:27 UTC
Labels: bug
