### ISSUE TITLE
@JsonbCreator should allow properties to be optional

### ISSUE THREAD

**Issue by derekm** [eclipse-ee4j/yasson#285] opened 2019-07-25 15:38 UTC
When using `@JsonbCreator` with `@JsonbProperty`, the creator factory/constructor cannot overcome situations where the property being called for is null-squashed by the remote service.

`@JsonbCreator`-instantiated objects should allow properties to be optional or null-squashed, even when `@JsonbProperty` is used.

**Comment by ivangreene** [comment] 2019-07-25 15:39
Demo test case. Uncomment `@JsonbCreator` to see the exception: `javax.json.bind.JsonbException: JsonbCreator parameter bar is missing in json document.`
```java
public class MissingValuesTest {

    public static class Container {
        public Long foo;
        public Long bar;

        public Container() {
        }

//        @JsonbCreator
        public Container(@JsonbProperty("foo") Long foo, @JsonbProperty("bar") Long bar) {
            this.foo = foo;
            this.bar = bar;
        }
    }

    @Test
    public void shouldBeOkWithMissingValues() {
        Jsonb jsonb = JsonbBuilder.create();
        Container container = jsonb.fromJson("{\"foo\":3}", Container.class);
    }
}
```

**Comment by m0mus** [comment] 2019-07-26 08:58
Duplicate of #237

**Comment by m0mus** [comment] 2019-07-26 09:00
We are working on #237 now. Summary is, it's against the current spec, but we are thinking of adding it to Yasson as an experimental feature.

**Closed by m0mus** 2019-07-26 09:00 UTC

**Comment by ivangreene** [comment] 2019-07-26 14:20
@m0mus thanks for a quick response. Interesting to note is Johnzon's approach: https://github.com/apache/johnzon/commit/6c610cf03164236c39214873001bc46f513c5eda
They added a config property to disable this behavior, so by default they are spec compliant in this regard but users can opt out

**Comment by aguibert** [comment] 2019-07-29 16:15
IMO optional constructor properties are one of the top 3 most needed features for JSON-B, and I will be pushing hard for this feature to be standardized at the spec level, which is currently being discussed here:
https://github.com/eclipse-ee4j/jsonb-api/issues/121

For the sake of not needing to have two different implementations of optional ctor properties in Yasson, my preference is to wait until this is defined at the spec level (which will hopefully be soon).

**Comment by tsfullman** [comment] 2021-11-17 18:07
looks like a merge request went in and closed that referenced json b feature at the spec level allowing optional json parameters. Any plans to update yasson to support that now?
