### ISSUE TITLE
JsonObjectDeserializer getObject() cannot resolve method

### ISSUE THREAD

**Issue by scrmtrey91** [eclipse-ee4j/yasson#178] opened 2018-11-14 08:44 UTC
In class JsonObjectDeserializer it looks like it is missing method getObject() from JsonbParser class. (IntellIj IDEA)

`@Override
    protected void deserializeInternal(JsonbParser parser, Unmarshaller context) {
        this.jsonObject = parser.getObject();
    }`

[JsonObjectDeserializer.java](https://github.com/eclipse-ee4j/yasson/blob/master/src/main/java/org/eclipse/yasson/internal/serializer/JsonObjectDeserializer.java)

And maybe this causing the issue with JAX-RS when it readEntity(JsonObject.class) from jax.ws.rs response. (i think it is unsupported operation or unknow operation)

Maybe if you could check this. It is the same in version 1.0 and version 1.0.2.

**Comment by aguibert** [comment] 2018-11-15 01:57
hi @scrmtrey91, I'm not quite sure what the issue is you are trying to point out here.  Are you suggesting that the `JsonbParser.getObject()` method doesn't exist?  That is not the case, if so it would be causing a compile failure in the Yasson build.

Do you have a stack trace or something for the error you are referring to?

**Comment by scrmtrey91** [comment] 2018-11-15 06:41
![jsonobjectdeserializeryassonmethod](https://user-images.githubusercontent.com/24773401/48534780-6a93fa80-e8a9-11e8-8afb-35e613d0ad4f.PNG)

Check the image and you will see. I don't what cause this "issue".

If i will have time, i could revert the code and show the error message or stacktrace. But for now check the image if you have any idea.

**Comment by scrmtrey91** [comment] 2018-11-15 14:44
Our project itself is compiling correctly. Also no problem with deploying and running the app.

I did not try to checkout yasson git and run mvn clean install.

But as you said maybe it is IDE problem (somehow).

**Comment by scrmtrey91** [comment] 2018-11-15 15:06
It looks like it was problem with mixed JavaEE dependency. Somehow it was using 7.0 instead of 8.0.

With 7.0 removed and only using 8.0, method is resolved correctly.

I will take time and make WS and client with same code as before, to see if the exception (unsuported operation) will still be an issue. I think this was causing the issue. 

Thanks for your help for now. When i will try this , i will make a comment again to give an updated information.

**Comment by aguibert** [comment] 2018-11-26 19:31
Closing this issue at seems to just be a random IDE bug.  We can re-open if the problem persists

**Closed by aguibert** 2018-11-26 19:31 UTC
