### ISSUE TITLE
withFormatting puts key/value pairs on separate lines

### ISSUE THREAD

**Issue by swpalmer** [eclipse-ee4j/yasson#128] opened 2018-05-25 20:48 UTC
The current formatted output is difficult to read. Since formatting is all about making the JSON more human-readable, this should be improved.

I propose not adding a newline after the ':' so that key/value pairs are on the same line, unless the value will also need to be multi-line (i.e. is itself a multi-value entity). This will keep value data distinct from key names.

So this:
```
{
    "x": 
    "y"
}
```

becomes:
```
{
    "x": "y"
}
```

and this:
```
{
    "subgroup": 
    {
        "a": 
        "1",
        "b": 
        "2",
        "d": 
        {
            "age": 
            3,
            "bitable": 
            true,
            "name": 
            "Rover"
        }
    },
    "x": 
    "y"
}
```

becomes:
```
{
    "subgroup":
    {
        "a": "1",
        "b": "2",
        "d":
        {
            "age": 3,
            "bitable": true,
            "name": "Rover"
        }
    },
    "x": "y"
}
```

**Comment by m0mus** [comment] 2018-05-28 09:39
This is an issue in JSONP which is fixed. New version of JSONP containing this fix is not yet released.  It will be fixed in Yasson when that new version is adopted.
Duplicate of https://github.com/eclipse-ee4j/yasson/issues/89

**Closed by m0mus** 2018-05-28 09:39 UTC
