### ISSUE TITLE
"fromJson" with EnumSet

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#291] opened 2019-08-02 09:14 UTC
Would be nice to be able to (de)serialize EnumSets.

`
SEVERE [org.eclipse.yasson.internal.Unmarshaller] Can't create instance of a class: class java.util.EnumSet, No default constructor found.`

Something like this does not work with:

```
var jsonb = JsonbBuilder.create();
jsonb.fromJson(json, EnumSet.noneOf(Task.class).getClass().getGenericSuperclass());
```

**Comment by aguibert** [comment] 2019-08-05 14:54
hi @nimo23, you are right that the currently released version of Yasson does not support EnumSet.

Support for EnumSet was very recently added under PR #287, and will be included in the next release of Yasson (1.0.5).

Closing this issue as a duplicate of #272.

**Closed by aguibert** 2019-08-05 14:54 UTC
Labels: duplicate
