### ISSUE TITLE
Illegal access warnings with OpenJDK 15

### ISSUE THREAD

**Issue by gunnarmorling** [eclipse-ee4j/yasson#412] opened 2020-05-24 09:32 UTC
**Describe the bug**
I'm getting these warnings with Yasson 1.0.7:

```
WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (file:/path/to/org.eclipse.yasson-1.0.7.jar) to constructor java.util.AbstractCollection()
WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (file:/path/to/org.eclipse.yasson-1.0.7.jar) to constructor java.util.AbstractList()
```

While functionality of the application isn't impacted, the warning creates noise, and the default option in a future JDK will be to disallow these reflective access.

**To Reproduce**
Serialize/deserialize e.g. a collection class.

**Expected behavior**
No warning should be printed, reflection should not be unconditionally applied.

**System information:**
 - OS: macos
 - Java Version: JDK 15-ea+24-1168
 - Yasson Version: [e.g. 1.0.7]

**Additional context**
-

**Comment by Degubi** [comment] 2020-06-02 08:50
Was unable to reproduce this error using this code:

```java
var jsonb = JsonbBuilder.create();
        
        var coll1 = List.of("test1");
        var coll2 = Map.of("hi", "there");
        
        var toJson1 = jsonb.toJson(coll1);
        var fromJson1 = jsonb.fromJson(toJson1, List.class);
        
        var toJson2 = jsonb.toJson(coll2);
        var fromJson2 = jsonb.fromJson(toJson2, Map.class);
        
        System.out.println(toJson1);
        System.out.println(fromJson1);
        System.out.println(toJson2);
        System.out.println(fromJson2);
```

**Comment by gunnarmorling** [comment] 2020-06-02 08:58
Could you try with a bean that has a list/map as a member?

**Comment by Degubi** [comment] 2020-06-02 09:13
Tried with this @gunnarmorling :
```java
public class Main {

    public static void main(String[] args) {
        var jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(Boolean.TRUE));
        
        var data = new TestData();
        var toJson1 = jsonb.toJson(data);
        var fromJson1 = jsonb.fromJson(toJson1, TestData.class);
        
        System.out.println(toJson1);
        System.out.println(fromJson1);
    }
    
    public static class TestData {
        
        public final List<String> data1 = List.of("test");
        public final Map<String, String> data2 = Map.of("hi", "sup");
        
        @Override
        public String toString() {
            return data1.toString() + ' ' + data2.toString();
        }
    }
}
```

This printed the following without errors:
```
{
    "data1": [
        "test"
    ],
    "data2": {
        "hi": "sup"
    }
}
[test] {hi=sup}
```

Also tried going back a few commits (I thought maybe something fixed this), but still got no warnings. :/

**Comment by gunnarmorling** [comment] 2020-06-02 09:59
So I went back to see what I did and reate a reproducer, but turns out your first example exposes the issue for me already. Here's exactly what I'm doing:

```
java --version
openjdk 15-ea 2020-09-15
OpenJDK Runtime Environment (build 15-ea+24-1168)
OpenJDK 64-Bit Server VM (build 15-ea+24-1168, mixed mode, sharing)

cat > Test.java <<EOF
import java.util.List;
import java.util.Map;

import javax.json.bind.JsonbBuilder;

public class YassonTest {

    public static void main(String[] args) {
        var jsonb = JsonbBuilder.create();

        var coll1 = List.of("test1");
        var coll2 = Map.of("hi", "there");

        var toJson1 = jsonb.toJson(coll1);
        var fromJson1 = jsonb.fromJson(toJson1, List.class);

        var toJson2 = jsonb.toJson(coll2);
        var fromJson2 = jsonb.fromJson(toJson2, Map.class);
    }
}
EOF

java --class-path=/Users/gunnar/.m2/repository/org/glassfish/jakarta.json/1.1.6/jakarta.json-1.1.6.jar:/Users/gunnar/.m2/repository/org/eclipse/yasson/1.0.7/yasson-1.0.7.jar:/Users/gunnar/.m2/repository/jakarta/json/bind/jakarta.json.bind-api/1.0.2/jakarta.json.bind-api-1.0.2.jar Test.java

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (file:/Users/gunnar/.m2/repository/org/eclipse/yasson/1.0.7/yasson-1.0.7.jar) to constructor java.util.AbstractCollection()
WARNING: Please consider reporting this to the maintainers of org.eclipse.yasson.internal.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Which Java version are you on?

**Comment by Degubi** [comment] 2020-06-15 16:45
I managed to reproduce it with 1.0.7. It was a mistake on my end...
I was unable to reproduce it with 2.0.0-M2.
Can you guys try with that version? @gunnarmorling @edufolly

**Comment by aguibert** [comment] 2020-06-15 17:40
This issue has been fixed in 2.X stream as @Degubi noted by this PR: https://github.com/eclipse-ee4j/yasson/pull/403

And the fix has already been backported to 1.X here: https://github.com/eclipse-ee4j/yasson/pull/401

So the fix will be included in the next release of Yasson 1.X (1.0.8). Closing this one ad a dup of https://github.com/eclipse-ee4j/yasson/pull/401

**Closed by aguibert** 2020-06-15 17:40 UTC
Labels: bug
