### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#298] opened 2019-08-09 12:10 UTC
I get this error while trying to convert an entity to json string and the **stacktrace does not show me which property makes trouble**. So I search like a needle in a haystack. Please add at least the property which makes trouble.

By the way, using exactly the same bean hierarchy and converting to json string with Jackson does not throw any `java.lang.OutOfMemoryError` and json output is sucessfully. But with Yasson, converting the same bean hierarchy to json string does not work and throws this stacktrace:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3746)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:686)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:409)
	at java.base/java.io.StringWriter.write(StringWriter.java:99)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:651)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.writeString(JsonGeneratorImpl.java:608)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.writeString(JsonGeneratorImpl.java:614)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonPrettyGeneratorImpl.writeIndent(JsonPrettyGeneratorImpl.java:108)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonPrettyGeneratorImpl.writeComma(JsonPrettyGeneratorImpl.java:116)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.writeName(JsonGeneratorImpl.java:171)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonGeneratorImpl.writeKey(JsonGeneratorImpl.java:489)
	at org.glassfish.javax.json@1.1.2//org.glassfish.json.JsonPrettyGeneratorImpl.writeKey(JsonPrettyGeneratorImpl.java:53)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:88)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:103)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializeItem(AbstractContainerSerializer.java:157)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:39)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.CollectionSerializer.serializeInternal(CollectionSerializer.java:27)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson//org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:103)
```

**Comment by aguibert** [comment] 2019-08-09 18:59
hi @nimo23, I'm going to close this issue as a duplicate of #299. It looks like the root problem for both issues is the same -- there is an infinite recursive loop happening somewhere. It just happens to manifest itself as a StackOverflow in some cases and a OutOfMemory in other cases.

**Comment by aguibert** [comment] 2019-08-09 18:59
also, we can use #297 for the general case of including property name whenever there is an unknown serialization failure

**Closed by aguibert** 2019-08-09 18:59 UTC
Labels: duplicate
