### ISSUE TITLE
Deserializing with generic types has different behavior using @JsonbCreator

### ISSUE THREAD

**Issue by ivangreene** [eclipse-ee4j/yasson#284] opened 2019-07-25 14:24 UTC
Deserializing a POJO with generic collection types (Set, Map) has different behavior when using `@JsonbCreator` annotated constructor. When the values of these types are specified as an Enum, they work as expected when Jsonb populates them as fields. However, when using a `@JsonbCreator` annotated constructor or static factory, the values of these members will be String at runtime.

In this example, the JsonbCreator annotation can be commented out to observe the test passing.

```java
public class EnumValueTest {

    public static class Container {
        public Map<String, Letter> nameToLetter;
        public Set<Letter> letters;

        public Container() {
        }

        @JsonbCreator
        public Container(@JsonbProperty("nameToLetter") Map<String, Letter> nameToLetter, @JsonbProperty("letters") Set<Letter> letters) {
            this.nameToLetter = nameToLetter;
            this.letters = letters;
        }
    }

    @Test
    public void shouldHaveEnumValues() {
        Jsonb jsonb = JsonbBuilder.create();
        Container container = jsonb.fromJson("{\"nameToLetter\":{\"a\":\"A\"}, \"letters\":[\"A\"]}", Container.class);
        assert container.letters.iterator().next() instanceof Letter : "set member is Letter";
        assert container.letters.iterator().next() == Letter.A : "member == A";
        assert container.nameToLetter.values().iterator().next() instanceof Letter : "value is Letter";
        assert container.nameToLetter.values().iterator().next() == Letter.A : "value == A";
    }

    enum Letter {
        A, B, C
    }
}
```

**Comment by Degubi** [comment] 2019-12-20 16:47
Tested with current version, was unable to reproduce.
Tested with 1.0.5, 1.0.4: unable to reproduce.
Tested with 1.0.3 and was able to reproduce what the user described.

**Comment by aguibert** [comment] 2019-12-21 00:11
Thanks for testing @Degubi, looks like it may have been resolved by this PR: https://github.com/eclipse-ee4j/yasson/pull/202

Closing this issue since it is no longer occurring

**Closed by aguibert** 2019-12-21 00:11 UTC
Labels: bug
