### ISSUE TITLE
Yasson on SpringBoot: IOException Stream Closed

### ISSUE THREAD

**Issue by amihaiemil** [eclipse-ee4j/yasson#389] opened 2020-03-16 14:24 UTC
Hi guys,

In Spring Boot 2.2.5, one can choose their own json provider.

1. Exclude the default Jackson
2. Add the Yasson dependency in pom.xml (which also brings the JSON-B API + JSON-P)

```xml
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>1.0.6</version>
    <scope>runtime</scope>
</dependency>
```
3. Specify in ``application.properties`` the following:
``spring.http.converters.preferred-json-mapper=jsonb``

This setup seems to work like a charm, except the logs contain an error at each request:

```
2020-03-16 16:09:20.306 ERROR 1540 --- [io-8090-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.io.IOException: Stream closed
        at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45) ~[na:1.8.0_202]
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140) ~[na:1.8.0_202]
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) ~[na:1.8.0_202]
        at org.springframework.http.converter.json.AbstractJsonHttpMessageConverter.writeInternal(AbstractJsonHttpMessageConverter.java:130) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:287) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:226) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.31.jar:9.0.31]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]


2020-03-16 16:09:20.354 ERROR 1540 --- [io-8090-exec-10]
s.e.ErrorMvcAutoConfiguration$StaticView : Cannot render error page for request [/country] and exception [Stream closed] as the response has already been committed. As a result, the response may have the wrong status code.

```

Apparently more people are having the same issue. See [here](https://stackoverflow.com/questions/57023602/failed-to-complete-request-java-io-ioexception-stream-closed-from-spring-boot) and [here](https://github.com/fuinorg/ddd-cqrs-4-java-example/issues/4).

Any idea why this could happen? Do you think it's a bug in Yasson or in Spring Boot?
Since the error does not occur with Jackson, I assume it could also be a bug in Yasson.

**Comment by aguibert** [comment] 2020-03-16 14:54
hi @amihaiemil , can you please include the full stack trace? That will give us an idea of the exception flow. What's currently shown has no yasson classes in the stack so I have no idea what close flow we are in

**Comment by amihaiemil** [comment] 2020-03-16 15:05
@aguibert I updated the description with the full stacktrace. Thank you!

**Comment by aguibert** [comment] 2020-03-16 15:10
After the Spring message converter is done calling out do JSON-B to write to a `java.io.Writer` it then calls flush(), but Yasson is closing the Writer after writing the JSON object. 

I see two options here:
A) Spring boot could call `writer.close()` instead of `writer.flush()`. Close will first do a flush, but it will safely no-op if the writer is already closed
B) Yasson could not implicitly close the writer after calling `toJson`

I'm not finding any wording in the spec or javadoc that says an implementation should or should not close a Writer, but it would make more sense if the Writer was left open. I will try to make that change and see if it effects any existing test scenarios.

**Comment by amihaiemil** [comment] 2020-03-16 15:14
@aguibert well, I think if Yasson doesn't close the Writer, that could be treated as a Memory Leak of sorts, or? I think Writers should be closed when whoever writes has finished writing.

**Comment by amihaiemil** [comment] 2020-03-16 15:18
@aguibert Well, someone from Spring Boot answered. They are apparently convinced it's a bug in Yasson.

**Comment by aguibert** [comment] 2020-03-16 15:19
I think it could go either way. Since the user is passing in the writer, they still hold a reference to the Writer and could close it on their own -- but this way is more error prone. 

I ran a quick test and confirmed that yasson can _not_ change behavior here. We have some basic scenarios that would break if we stopped closing the writer, for example:
```java
        Writer writer = new StringWriter();
        bindingJsonb.toJson(new Long[]{5L}, writer);
        String writerValue = writer.toString();
```
Current behavior is that `writerValue` is `[5]` but if we don't close the writer then the user gets an empty string.

**Comment by wilkinsona** [comment] 2020-03-16 15:20
FWIW, the user would get the expected string if Yasson called `flush()` rather than `close()` with the added benefit that they can then continue to use the writer if they wish to do so.

**Comment by amihaiemil** [comment] 2020-03-16 15:22
@wilkinsona @aguibert Both Issues are closed now, yet this is clearly a bug. Andrew says Yasson cannot change behaviour. @wilkinsona maybe we can do something on Spring Boot's side,?

**Comment by aguibert** [comment] 2020-03-16 15:22
that's a good compromise @wilkinsona, I'll re-open this issue

**Comment by amihaiemil** [comment] 2020-03-24 19:08
@aguibert Can you please let me know as soon as this fix is released and with what version? Many thanks 💯

**Comment by aguibert** [comment] 2020-03-28 15:44
@amihaiemil sure, I'll post back when we cut the next release -- it will be Yasson 1.0.7. I'm going to take a look through our existing bug backlog and see if we can clear out more items before I cut that release though. 

Closing this issue though since fixes are delivered now.

**Closed by aguibert** 2020-03-28 15:44 UTC
Labels: bug

**Comment by aguibert** [comment] 2020-04-07 19:43
hi @amihaiemil, Yasson 1.0.7 is now released and should contain the fix for this issue

**Comment by amihaiemil** [comment] 2020-04-08 06:15
@aguibert thanks a lot!
