### ISSUE TITLE
annotations within class should have higher precedence than class annotations

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#304] opened 2019-08-10 14:35 UTC
I have this:

```
@JsonbVisibility(value = PrivateVisibilityStrategy.class)
public class Task{

@JsonbProperty(nillable = true)
public Set<Item> getItems(){
return ...;
}
}
```

Now, even I explicitly assign `@JsonbProperty` on a getter,  the value is **not** (de)serialized because of `@JsonbVisibility(value = PrivateVisibilityStrategy.class)`. Is this okay? If I choose to select a getter to (de)serialize as an exception, then json-b should take the inner annotation with higher priority than the class level annotation. 

**So the precedence should be (from higher to lower):**

**runtime configuration > property/getter/setter annotations > class level annotations**

**Comment by aguibert** [comment] 2019-08-10 20:02
This issue on the JSON-B spec repo looks similar to what you are suggesting:
https://github.com/eclipse-ee4j/jsonb-api/issues/61

If you agree, we can close this issue as a duplicate of it

**Comment by nimo23** [comment] 2019-08-11 00:58
yes, close this issue, if you think it s the same.

**Closed** 2019-08-11 03:40 UTC
Labels: duplicate
